### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by maxrd2**
Enjoy!

### CODE REVIEW

**Comment by muzena** [comment]
@maxrd2 
When I making PPA repo I register Subtitlecomposer project, I didn't look before into options for translating, I look before two weeks little code options in Subtitlecomposer project so I activated Subtitle project translation system https://translations.launchpad.net/subtitlecomposer/+translations#

**Comment by maxrd2** [comment]
I don't understand. I suppose translations can be merged/committed here when they are done in launchpad.
Have setup Crowdin account, so the translations can be committed easily without translators having to use git or other potentially complicated tools for non-techy people. Also it gives a quick overview of translation status, like before publishing new version.

**Comment by muzena** [comment]
Problem with Launchpad is it can't auto merged back to github.
Isn't transifex better than crowdin?

**Comment by maxrd2** [comment]
I don't know. Why is it better? Have been trying a bunch solutions online for few days.
Have liked crowdin's features and integration better than what I've seen on other platforms.
I haven't tried transiflex because zillion of different google searches failed to put it among results.
What's wrong with crowdin?

**Comment by muzena** [comment]
https://www.transifex.com
For me transifex is better, better more logical gui, and have translation teams,
here on crowdin I don't understand this voting.

I don't understand this:
Num of speech frames to trigger vad from silence to speech
Što je vad

Noise Treshold
Threshold for decision between noise and silence frames. Log-ratio between signal level and noise leve
Zadnja riječ je level, fali l?
noise - misli li se na buku ili šum
Log-ratio - to mi nije jasno što je
Noise Treshold

**Comment by maxrd2** [comment]
Voice Activity Detection

**Comment by maxrd2** [comment]
log - logaritamski
ratio - odnos? npr 16:9 je ratio
Threshold for decision between noise and silence frames. Log-ratio between signal level and noise leve
Granica odlučivanja između buke i tišine. Odnos između nivoa signala i buke. :)
Malo je znanstveno, ali je to ASR

**Comment by maxrd2** [comment]
Crowdin voting? You mean proofreading?
Suppose there are 5 translators translating text in same language, Several translators suggest/write different translation. Proofreader approves the translation which he believes is the best.

**Comment by muzena** [comment]
Aaaha, proofreader it's like reviewer in other translating services.
Za log sam mislio da je zapis ili dnevnik tako nešto, a to je logaritam. :)

**Pull request closed without merging**
