### PR TITLE
fixed displaying icons under non-KDE desktop environments

### PR DESCRIPTION
**Pull request by Martchus**
- by providing a fallback icon path
- cleanup of configdialog.{h,cpp} by the way

### CODE REVIEW

**Comment by maxrd2** [comment]
Thanks for this patch.
It seems it's because QT doesn't load frameworksplugin in non plasma envrionments, and that plugin looks for fallback icons in other themes and share/appname path.
Came across some discussion here: https://mail.kde.org/pipermail/kde-frameworks-devel/2014-September/018818.html

I prefer to do it without hardcoding fallback icon paths. Will look some more if I can come up with some "cleaner" way. If not will merge this.

**Comment by Martchus** [comment]
I don't think any GNOME/Cinnamon user wants Qt 5 applications to load the KDE plattform integration plugin. This plugin is meant to integrate Qt apps in the Plasma desktop by using the Plasma settings and dialogs. Using it in other environments is not appropriate and might even break something.

The hard coded approach I implemented is only used as a fallback when the current dynamic one fails. I think this should work in most cases and can be used until a better way is found and implemented.

Other solutions I can think of (these would require a bit more coding):
- Adding the icons to the applications resources.
- Allow the user to configure the location of the icons and use the hard coded version only as last fallback.
- Just put the icons under /usr/share/icons/hicolor since this is always used as fallback. Icon names might be unified before to avoid conflicts.

By the way, the path of the translation files seems to be hard coded, too. But unfortunately not like my approach which will automatically hard code the right install directory. So I can not test the translations conveniently because always the regularly installed *.mo file is used.

**Comment by maxrd2** [comment]
There are quite few icons that are loaded from /usr/share/subtitlecomposer/pics/ path which was fine with KIcon in KDE4. After porting to KF5 and changing KIcon("icon-name") to QIcon::fromTheme("icon-name") I caused this issue.

Since none of those icons are part of any theme, maybe it would be better to just hardcode the paths and load them directly from CUSTOM_ICON_INSTALL_PATH. e.g. 
```c++
item->setIcon(QIcon(QStringLiteral(CUSTOM_ICON_INSTALL_PATH "mediaplayer-logo")));
```
instead of:
```c++
item->setIcon(QIcon::fromTheme(QStringLiteral("mediaplayer-logo"), QIcon(QStringLiteral(CUSTOM_ICON_INSTALL_PATH "mediaplayer-logo"))));
```
since it's not a themed icon name don't think anyone will provide an action icon in any theme for "current-line-follows-video" or "set-show-time" anytime soon.

Sorry for the rant, just want to do it proper way, and am not sure what's the proper way.

**Comment by Martchus** [comment]
The icons provided by Subtitle Composer are not part of a regular theme - that's true.

However dynamically resolving the path works anyways under KDE because it seems like their icon engine takes care of it. That's the reason why I left the dynamic version there. If you want to remove them it is ok, too.

I also created a patch which resolves the full screen issue.

**Comment by maxrd2** [comment]
Thanks :)

**Pull request merged**
